### ISSUE TITLE
Moon Phase power crash on use

### ISSUE THREAD

**Issue by gygrazok** [lionpkqq/StS-BlackRuseMod#1]
Immediately after using the card the game crashes with the following error:
`Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
	at blackrusemod.cards.MoonPhase.use(MoonPhase.java:32)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1464)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:284)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:256)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2616)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:820)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:415)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NullPointerException
	at blackrusemod.powers.MoonPhasePower.<clinit>(MoonPhasePower.java:15)
	... 10 more`

I think this is related to the english localization strings: in BlackruseMod-PowerStrings-eng.json the definition for MoonPhasePower is missing (there is only the definition for MoonPhase)

**Comment by lionpkqq** [comment]
Thanks for helping me locate the bug! A fix will be released with the next update!

Believe or not, it was an accident that the effects of Decrepit and Blight are exactly the same. Anyway, keep up the good work!
