### ISSUE TITLE
Mod CTD after starting a game

### ISSUE THREAD

**Issue by KongMD-Steam** [lionpkqq/StS-BlackRuseMod#19]
## Expected Behavior
Pressing 'Play' starts a new game.

## Actual Behavior
The game crashes after pressing 'Play'. This is being caused by the newest version of BaseMod, v3.1.0. I do not get this crash on v3.0.2. Stack trace:

```
12:58:13.201 INFO basemod.BaseMod> Adding Custom Events...
12:58:13.220 INFO dungeons.AbstractDungeon> INIT CARD POOL
Exception: java.lang.NullPointerException
12:58:13.222 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeCardPoolsSwitch.Insert(InitializeCardPoolsSwitch.java:58) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeCardPools(AbstractDungeon.java:1571) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.<init>(AbstractDungeon.java:360) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:50) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1370) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.
```
## Mods active
1) BaseMod 3.1.0
2) Black Ruse 0.9.2

**Comment by lionpkqq** [comment]
@kiooeht

**Comment by kiooeht** [comment]
Yup, this is my fault. Fix coming for BaseMod soon.

**Comment by kiooeht** [comment]
Fix is out (https://github.com/daviscook477/BaseMod/releases/tag/v3.1.1). Should be good to close this issue.
