### ISSUE TITLE
Crash log when picking rearm

### ISSUE THREAD

**Issue by smonheim** [lionpkqq/StS-BlackRuseMod#20]
If due to another mod let me know and I'll post elsewhere. Thanks!

## Expected Behavior
Receive card when picked

## Actual Behavior
Crash

## Steps to Reproduce the Problem

  1. Haven't been able to reproduce it

## Specifications

  - Version: 0.9.2, StS v8/30/18 beta
  - Platform: Linux
 
Terminal output:

01:27:40.104 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: QUEST_LOG_SCREEN
01:27:44.804 INFO unlock.UnlockTracker> Already seen: Blood Vial
01:27:45.104 INFO unlock.UnlockTracker> Already seen: Foresight
01:27:45.105 INFO unlock.UnlockTracker> Already seen: Rearm
01:27:45.108 INFO unlock.UnlockTracker> Already seen: LightFlow
01:27:47.528 INFO helpers.CardHelper> Obtained Rearm (COMMON). Creating new map entry.
**01:27:47.529 INFO unlock.UnlockTracker> Already seen: Rearm
Exception: java.lang.NullPointerException
01:27:47.543 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:1.8.0_131]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)** ~[?:1.8.0_131]
	at java.lang.reflect.Field.set(Field.java:764) ~[?:1.8.0_131]
	at com.evacipated.cardcrawl.modthespire.lib.SpireField.set(SpireField.java:45) ~[ModTheSpire.jar:?]
	at infinitespire.relics.BottledSoul.bottleCard(BottledSoul.java:162) ~[InfiniteSpire.jar:?]
	at infinitespire.relics.BottledSoul.onMasterDeckChange(BottledSoul.java:79) ~[InfiniteSpire.jar:?]
	at com.megacrit.cardcrawl.vfx.FastCardObtainEffect.update(FastCardObtainEffect.java:56) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2785) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active

**Comment by lionpkqq** [comment]
Maybe there is another card called Rearm from other mods you have installed. Could you recall anything like that?

**Comment by smonheim** [comment]
Mods installed are, Infinite Spire, Replay the Spire, Black Ruse, Always Whale, and Colored Map.

I don't think any of those mods have a rearm card. I just searched them in case and didn't see one. Odd part is that a previous run on the same install today had no issues with rearm.

If I get another crash I'll get the log again for you. I'll pipe the whole run log into a txt file just in case.

**Comment by smonheim** [comment]
Just happened with WasteNot. Log attached, sorry for the large log. Let me know if there's something I can do to help. Not a big Java guy, but still a SWE as my job.

Running with debug mode turned ON...
[log.txt](https://github.com/lionpkqq/StS-BlackRuseMod/files/2346885/log.txt)

**Comment by lionpkqq** [comment]
It's definitely caused by other mods but I couldn't tell which one it was. Potentially cause by [?:1.8.0_131] or [InfiniteSpire.jar:?].

**Comment by smonheim** [comment]
Copy that, i'll move this along to them!
