### ISSUE TITLE
Broken on Latest Weekly Patch

### ISSUE THREAD

**Issue by kiooeht** [lionpkqq/StS-BlackRuseMod#24]
When trying to start any run as The Servant, you instead get Ironclad.

```
19:40:44.340 ERROR basemod.BaseMod> could not instantiate blackrusemod.characters.TheServant with the constructor blackrusemod.characters.TheServant
19:40:44.345 INFO basemod.BaseMod> running as the Ironclad instead
19:40:44.346 ERROR basemod.BaseMod> error was: null

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at basemod.BaseMod.createCharacter(BaseMod.java:1558)
        at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.CreateCharacterSwitch.Insert(CreateCharacterSwitch.java:32)
        at com.megacrit.cardcrawl.core.CardCrawlGame.createCharacter(CardCrawlGame.java:1279)
        at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:831)
        at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.core.Settings.dailyModsEnabled()Z
        at blackrusemod.characters.TheServant.<init>(TheServant.java:49)
        ... 11 more
```

Crash is caused by line 49 of TheServant.java
https://github.com/lionpkqq/StS-BlackRuseMod/blob/80856a74d1adfd7244883b0c82006538af5e5b6f/src/main/java/blackrusemod/characters/TheServant.java#L49

The Week 43 patch changed how daily modifiers are handled, hence the crash. You can just remove that entire if statement since BaseMod handles giving a character an orb slot.

**Comment by SilentJ28** [comment]
Need to remove the import too:
import com.megacrit.cardcrawl.daily.DailyMods;

**Comment by lionpkqq** [comment]
Thanks, guys. The next update will fix this issue.
