### ISSUE TITLE
Crash on win/death.

### ISSUE THREAD

**Issue by MIC132** [lionpkqq/StS-BlackRuseMod#25]
So, with the newest version (and obviously up-to-date version of Slay the Spire, Mod the Spire, and the Base Mod) I'm getting a crash each time I die or win with this character.

I'm quite sure this is somehow related to the unlock system, since the issue didn't appear at first, only after I got through the first 2 unlocks. (I'm currently at 3 remaining and around 650/1000 till next).

The game just crashes to desktop, and no progress seems to be saved. Neither can I continue the run (so the game acknowledges it ended, I guess), not does my unlock progress go up (so somehow the score is ignored).

Otherwise a *brilliant* mod, though I might be biased since I love Touhou.

**Comment by lionpkqq** [comment]
`04:47:57.884 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\THE_SERVANT
04:47:57.884 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\THE_SERVANT
04:47:57.884 INFO helpers.AsyncSaver> Enqueue: qsize=0 file=preferences\THE_SERVANT
04:47:57.885 INFO helpers.AsyncSaver> Enqueue: qsize=1 file=preferences\THE_SERVANT
04:47:57.885 INFO saveAndContinue.SaveAndContinue> DELETING THE_SERVANT SAVE
70.58533
Exception: java.lang.NullPointerException
04:47:57.888 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\THE_SERVANT
04:47:57.888 INFO helpers.FileSaver> Dequeue: qsize=1 file=preferences\THE_SERVANT
04:47:57.887 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at basemod.abstracts.CustomUnlock.<init>(CustomUnlock.java:11) ~[BaseMod.jar:?]
	at basemod.abstracts.CustomUnlockBundle.getUnlocks(CustomUnlockBundle.java:20) ~[BaseMod.jar:?]
	at basemod.patches.com.megacrit.cardcrawl.unlock.UnlockTracker.GetUnlockBundleSwitch.Postfix(GetUnlockBundleSwitch.java:20) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.unlock.UnlockTracker.getUnlockBundle(UnlockTracker.java:831) ~[?:?]
	at com.megacrit.cardcrawl.screens.DeathScreen.calculateUnlockProgress(DeathScreen.java:576) ~[?:?]
	at com.megacrit.cardcrawl.screens.DeathScreen.<init>(DeathScreen.java:344) ~[?:?]
	at com.megacrit.cardcrawl.events.beyond.SpireHeart.buttonEffect(SpireHeart.java:266) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.events.AbstractEvent.update(AbstractEvent.java:116) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.events.beyond.SpireHeart.update(SpireHeart.java:166) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.VictoryRoom.update(VictoryRoom.java:30) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2671) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
04:47:57.889 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\THE_SERVANT
04:47:57.892 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\THE_SERVANT
04:47:57.892 INFO helpers.FileSaver> Dequeue: qsize=0 file=preferences\THE_SERVANT
04:47:57.892 INFO helpers.File> Attempting to save file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\THE_SERVANT
04:47:57.894 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\THE_SERVANT
Controllers: removed manager for application, 0 managers active
Game closed.`

**Comment by kiooeht** [comment]
I think you're right. For some reason `CustomUnlock` just assumes everything is a card unlock and there's nothing set up for relic unlocks.
I'll fix it in BaseMod, but it will likely involve a slight change in your code to work. I'll let you know.

**Comment by kiooeht** [comment]
This week's update (https://github.com/daviscook477/BaseMod/releases/tag/v3.5.0) includes a fix for this.

You will have to specify that a CustomUnlockBundle is relics to fix this issue on your end.
https://github.com/daviscook477/BaseMod/blob/bc1fd96649dcd367cd6acddfbcb91ee2c2642add/src/main/java/basemod/abstracts/CustomUnlockBundle.java#L17

**Comment by lionpkqq** [comment]
Should be fixed in the newest version.
