### ISSUE TITLE
Vision Effects crash when used by other characters

### ISSUE THREAD

**Issue by Moocowsgomoo** [lionpkqq/StS-BlackRuseMod#26]
When using a Vision card as another character besides the Servant, the game crashes with the following error:

`20:56:54.201 INFO basemod.BaseMod> publish on card use
Exception: java.lang.NullPointerException
20:56:54.270 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at blackrusemod.actions.VisionAction.update(VisionAction.java:52) ~[BlackRuseMod.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:257) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2677) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]`

Tested with Snipe and Returning Blade specifically.

**Comment by kiooeht** [comment]
This should be fixable by moving https://github.com/lionpkqq/StS-BlackRuseMod/blob/ab82ba0031ce6293991abcc1384a5bd78f219bab/src/main/java/blackrusemod/characters/TheServant.java#L47
to either `BlackRuseMod.receivePostInitialize()` or `VisionAction` as
```Java
if (BlackRuseMod.vs == null) {
    BlackRuseMod.vs = new VisionScreen();
}
```
