### ISSUE TITLE
Instant crash on loading

### ISSUE THREAD

**Issue by Jedi515** [lionpkqq/StS-BlackRuseMod#27]
Pretty much self-explanatory, but just in case - i go mod the spire, start the game, it keeps on loading till eventually it shows this and then loads a bunch of queue-dequeue attempt-save till eventually it stops trying and the game never launches.
Turned off this specific mod and game loaded just fine.
That's what the log says somewhere in the middle:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: GREMLIN_MATCH
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: GREMLIN_MATCH
	at blackrusemod.cards.KidneyShot.<init>(KidneyShot.java:32)
	at blackrusemod.BlackRuseMod.receiveEditCards(BlackRuseMod.java:326)13:34:33.143 INFO helpers.File> Successfully saved file=D:\Steam\SteamApps\common\SlayTheSpire\preferences\STSUnlocks
13:34:33.144 INFO helpers.FileSaver> Dequeue: qsize=113 file=preferences\STSSeenCards
13:34:33.144 INFO helpers.File> Attempting to save file=D:\Steam\SteamApps\common\SlayTheSpire\preferences\STSSeenCards

	at basemod.BaseMod.publishEditCards(BaseMod.java:2162)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:284)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)13:34:33.176 INFO helpers.File> Successfully saved file=D:\Steam\SteamApps\common\SlayTheSpire\preferences\STSSeenCards
```

Also offtopic, but why not using protection from... i think it's replay the spire? shares the same idea, but applies before temp. hp and there's a potion of shielding.

**Comment by Zeushobbit** [comment]
Yeah, can confirm this is affecting more than one person, I've got the exact some issue and error message whenever I try and launch the game with the servant active. Given where the error message occurs it looks like it might have something to do with the unlocks system. I can confirm that I followed the instructions to delete the servant sections from both Unlockprogress and its backup file.

Error Message extract:
22:31:45.227 INFO helpers.FileSaver> Dequeue: qsize=84 file=preferences\STSUnlocks
22:31:45.227 INFO helpers.File> Attempting to save file=D:\Games\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: GREMLIN_MATCH
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: GREMLIN_MATCH
	at blackrusemod.cards.KidneyShot.<init>(KidneyShot.java:32)
	at blackrusemod.BlackRuseMod.receiveEditCards(BlackRuseMod.java:326)
	at basemod.BaseMod.publishEditCards(BaseMod.java:2162)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:284)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)22:31:45.241 INFO helpers.File> Successfully saved file=D:\Games\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks

**Comment by Jedi515** [comment]
I think it's because it's trying to call for basemod.helpers.basemodcardtags instead of basemodtags in kindneyshot card, and since it can't find that one it just perishes.
