### ISSUE TITLE
Game crash after choosing Splendid Attire

### ISSUE THREAD

**Issue by KongMD-Steam** [lionpkqq/StS-BlackRuseMod#7]
## Expected Behavior
The game doesn't crash.

## Actual Behavior
The game crashes after choosing the Splendid Attire relic in the reward screen. It is reproducible, and always occurs. Debug log:
```

00:41:42.110 INFO basemod.BaseMod> publish on relic get
00:41:42.110 INFO unlock.UnlockTracker> Already seen: Singing Bowl
00:41:42.110 INFO basemod.BaseMod> publish on relic get
00:41:42.110 INFO unlock.UnlockTracker> Already seen: SplendidAttire
Exception: java.util.ConcurrentModificationException
00:41:42.111 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_144]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.core.OverlayMenu.update(OverlayMenu.java:69) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2718) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:820) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:415) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
00:41:42.120 INFO core.CardCrawlGame> PAUSE()
00:41:42.120 INFO core.CardCrawlGame> Game shutting down...
```

## Steps to Reproduce the Problem

  1. Load up the attached save with debug mode turned on. 
[THE_SERVANT_Splendid_Attire_Crash.zip](https://github.com/lionpkqq/StS-BlackRuseMod/files/2212090/THE_SERVANT_Splendid_Attire_Crash.zip)

## Mod Info

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-12-2018)
 - ModTheSpire (2.8.0)
Mod list:
 - basemod (2.16.0)
 - ReplayTheSpireMod (1.0.4)
 - fetchmod (1.1.0)
 - HexCores
 - coloredmap (1.3.1)
 - blackrusemod (0.6.0)   <-- The mod I'm using is actually version 0.6.1, but the version number is wrong in the code

## Specifications

  - Platform: Windows 8 x64

**Comment by lionpkqq** [comment]
0.6.2 should have fixed the issue. Make sure that you have also updated ModTheSpire and BaseMod. Otherwise, ModTheSpire wouldn't start.
